### ISSUE TITLE
当列表ParallaxRecyclerView不在顶部的时候

### ISSUE THREAD

**Issue by Blincheng** [xiaoyanger0825/Parallax#1]
当列表ParallaxRecyclerView不在顶部的时候，向下拉，拉过顶部，触发下拉动画，然后松手。这时候点击item不起作用。重新向上滑动后有恢复。

**Comment by Blincheng** [comment]
建议在Up的时候修改如下：
case MotionEvent.ACTION_UP: {
                if (isScrollToTop() && !isScrollToBottom()) {
                    animateRestore(true);
                } else if (!isScrollToTop() && isScrollToBottom()) {
                    animateRestore(false);
                } else if (isScrollToTop() && isScrollToBottom()) {
                    if (mDistance > 0) {
                        animateRestore(true);
                    } else {
                        animateRestore(false);
                    }
                }
                return super.onTouchEvent(event);
            }

**Comment by jianjunxiao** [comment]
确实有这个Bug，谢谢！

**Comment by jianjunxiao** [comment]
hello，你建议的方式修改的话出现了新的Bug，就是有时候会触发到UP时，既没有在顶部也没有在底部，导致列表被拉伸后不会动画恢复，现在是在MOVE中直接返回true，消费掉后续事件，可修复。代码已更新。还是非常谢谢你指出之前的Bug。

**Comment by Blincheng** [comment]
哈哈哈，楼主还是很棒的。
